### ISSUE TITLE
Inline presentation

### ISSUE THREAD

**Issue by finkelm** [alexgorbatchev/jquery-textext#125]
The addition of:

``` css
.text-core {display: inline-block;vertical-align: middle;} 
.text-core .text-wrap {position: relative;} 
.text-core .text-wrap textarea {left: 0;}
```

allows for inline by default presentation of the tag without ruining the any of the features. This may be preferable as changing this to block is much easier than getting it to be inline. Since this is a search item, I would image this is often used in this way.This isn't an issue, just a comment.
